name: Fly Deploy
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sed -i 's/simselect/simselect-dev/g' fly.toml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
