name: Update Releases

on:
  schedule:
    - cron:  '15 3 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Update releases
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: '3.12'
    - name: install dependencies
      run: python -m pip install -r requirements.txt
    - name: update releases
      run: python track_releases.py
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: update json
      run: python yaml2json.py
    - name: commit if necessary
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: simtools/*.yaml
        commit_message: Update yaml files from releases
    - name: commit if necessary
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: simtools/simtools.json
        commit_message: Update JSON from yaml files
